config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :news
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/news.rb
class News < ApplicationRecord
    belongs_to :user
    validates :title, presence: true, length: { minimum: 5, maximum: 255}
    validates :subtitle, presence: true, length: { minimum: 5, maximum: 255}
    validates :author, presence: true, length: { minimum: 5, maximum: 55}
    validates :description, presence: true, length: { minimum: 10, maximum: 10500}
    validates :link, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase }
  has_many :news, dependent: :destroy
  validates :username, presence: true, 
                      uniqueness: { case_sensitive: false }, 
                      length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                      uniqueness: { case_sensitive: false }, 
                      length: { maximum: 105 },
                      format: { with: VALID_EMAIL_REGEX }
                      
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
          flash[:alert] = "You must be logged in to perform that action"
          redirect_to login_path
        end
      end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
  end

  def index
    @news = News.all
  end

  def new
    @new = News.new
  end
  
  def edit
  end

  def create
    @new = News.new(new_params)
    @new.user = current_user
    if @new.save
      flash[:notice] = "El artículo de noticia ha sido guardado satisfactoriamente."
      redirect_to @new
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @new.update(new_params)
      flash[:notice] = "El artículo de noticia ha sido actualizado satisfactoriamente."
      redirect_to @new
    else
      render 'edit'
    end
  end

  def destroy
    @new.destroy
    redirect_to news_path
  end
  private
    def new_params
      params.require(:news).permit(:title, :subtitle, :author, :description, :link)
    end

    def set_article
      @new = News.find(params[:id])
    end

    def require_same_user
      if current_user != @new.user
        flash[:alert] = "Sólo puedes editar tus propias noticias"
        redirect_to @new
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
        redirect_to news_index_path if logged_in?
    end

    def about
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end
  
    def create
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        flash[:notice] = "Inicio de sesión exitoso"
        redirect_to user
      else
        flash.now[:alert] = "Hubo un error con tu inicio de sesión"
        render 'new'
    end
    end
  
    def destroy
      session[:user_id] = nil
      flash[:notice] = "Sesión finalizada"
      redirect_to root_path
    end
  
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, only: [:edit, :update]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def show
      @news = @user.news
    end
    
    def index
      @users = User.all
    end

    def new
      @user = User.new
    end

    def edit
    end

    def update
      if @user.update(user_params)
        flash[:notice] = "Tu información de usuario ha sido correctamente actualizada"
        redirect_to @user
      else
        render 'edit'
      end
    end

    def create
      @user = User.new(user_params)
      if @user.save
        flash[:notice] = "Bienvenido a Noticias Genosur #{@user.username}, Te has conectado exitosamente."
        redirect_to news_index_path
      else
        render 'new'
      end
    end

    def destroy
      @user.destroy
      session[:user_id] = nil
      flash[:notice] = "Cuenta de usuario y noticias asociadas eliminadas."
      redirect_to news_index_path
    end

    private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def require_same_user
      if current_user != @user
        flash[:alert] = "Sólo puedes editar tu propio perfil."
        redirect_to @user
      end
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = { size: 80})
      email_address = user.email.downcase
      hash = Digest::MD5.hexdigest(email_address)
      size = options[:size]
      gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
      image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
    end

end

app/views/layouts/_messages.html.erb
    <%= flash.each do |name, msg| %>
      <%= msg %>
      <% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar bg-dark data-bs-theme=dark navbar-expand-lg bg-body-tertiary" >
    <div class="container-fluid">
        <%= link_to "Noticias APP", root_path, class: "navbar-brand text-white", id: "logo" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <% if logged_in? %>
            <li class="nav-item">
              <%= link_to "Lista de Noticias", news_index_path, class: "nav-link bg-dark" %>
            </li>
            <% end %> 
            <% if logged_in? %>
            <li class="nav-item">
              <%= link_to "Bloggers", users_path, class: "nav-link bg-dark" %>
            </li>
            <% end %> 
            <% if logged_in? %>
              <li class="nav-item">
                <%= link_to "Publicar Noticia", new_news_path, class: "nav-link bg-dark" %>
              </li>
            <% end %>  
            <% if logged_in? %>
              <li class="nav-item">
                <%= link_to current_user.username, user_path(current_user), class: "nav-link bg-dark" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Logout', logout_path, class: "nav-link bg-dark", method: :delete %>
              </li>
              <li>
                <%= link_to "Ver tu Perfil", user_path(current_user), class: "nav-link bg-dark" %>
              </li>
              <li>
                <%= link_to "Editar tu Perfil", edit_user_path(current_user), class: "nav-link bg-dark" %>
              <li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'Log in', login_path, class: "nav-link bg-dark" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign up', signup_path, class: "nav-link bg-dark" %>
              </li>
            <% end %>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class= "h-100">
  <head>
    <title>NoticiasApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="d-flex flex-column h-100">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <footer class="footer mt-auto py-3 bg-dark">
      <div class="container text-center">
        <span class="text-light">Copyright © Yamir Pinto 2023</span>
      </div>
    </footer>
  </body>
</html>

app/views/news/_form.html.erb
<div class = "container">

  <% if @new.errors.any? %>
    <H2>Los siguientes errores previnieron la edición del artículo de noticia:</h2>
    <ul>
      <% @new.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %> 
  <div class="row justify-content-center">
    <%= form_with data: { turbo: false}, class: "shadow p-3 mb-3 bg-white rounded", model: @new do |f| %>
      <div class="container shadow-lg p-3 mb-5 bg-white rounded">
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label" %> <br/>
          <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Ingrese un título" %> <br/><br/>
          <%= f.label :subtitle, class: "col-2 col-form-label"  %><br/>
          <%= f.text_field :subtitle, class: "form-control shadow rounded", placeholder: "Ingrese un subtítulo" %> <br/><br/>
          <%= f.label :author, class: "col-2 col-form-label"  %><br/>
          <%= f.text_field :author, class: "form-control shadow rounded", placeholder: "Ingrese autor" %> <br/><br/>
          <%= f.label :link, class: "col-2 col-form-label"  %><br/>
          <%= f.text_field :link, class: "form-control shadow rounded", placeholder: "Inserte link de imagen" %> <br/><br/>
          <div class="col-10">
            <br/>
            <%= f.label :description, class: "col-2 col-form-label"  %><br/>
            <%= f.text_area :description, rows: 8, class: "form-control shadow rounded", placeholder: "Ingrese descripción" %> <br/><br/>
          </div>
        </div>
      </div>
      <div class="form-group row">
        <%= f.submit class: "btn btn-outline-dark btn-lg" %><br/>
      </div>
      <br/><br/>
      <% end %>
  </div>     
</div>

app/views/news/_new.html.erb
<div class="mx-auto" style="width: 80%;">
    <% @news.each do |new| %>
      <div class="card text-center">
        <img src=<%= new.link %> class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title"><%= new.title %></h5>
          <%= link_to new.user.username, user_path(new.user) %>          
          <p class="card-text"><%= new.subtitle %></p>
            <%= link_to "Mostrar", news_path(new), class: "btn btn-outline-success" %>
            <%= link_to "Edit", edit_news_path(new), class: "btn btn-xs btn-primary" %> 
            <%= link_to "Eliminar", news_path(new), method: :delete, 
                                                  data: { confirm: "Estás seguro que deseas borrar esta noticia?" }, 
                                                  class: "btn btn-xs btn-danger" %>                                    
        </div>
      </div>
  
    <% end %>
  </div>

app/views/news/edit.html.erb
<div class="page-content">
  <h1 class="text-center mt-4">Editando Noticia</h1>

<%= render 'form' %>

</div>

app/views/news/index.html.erb
<h1 class="text-center mt-4">Listado de Noticias</h1>
  
<%= render 'new' %>

app/views/news/new.html.erb
<div class="page-content">
  <h1 class="text-center mt-4">Creando una nueva noticia</h1>
  <%= render 'form' %>
</div>

app/views/news/show.html.erb
<h1 class="text-center mt-4"><%= @new.title %></h1>
  <div background-color: #000000;>
      <img src=<%= @new.link %> class="card-img-top" max-height ="600px";>
  </div>
  <br/><br/>
  <div class="container">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title"><%= @new.subtitle %></h4>
        <%= @new.user.username %>
        <h6 class="card-title"><%= @new.author %></h6>
        <h6 class="card-title"><%= @new.created_at %></h6><br/>
        <p class="card-text"><%= @new.description %></p>
        <div class="text-center">
          
            <%= link_to "Mostrar", news_path(@new), class: "btn btn-outline-success" %>
            <%= link_to "Edit", edit_news_path(@new), class: "btn btn-xs btn-primary" %> 
            <%= link_to "Eliminar", @new, method: :delete, data: { confirm: "Estás seguro que deseas borrar esta noticia?" }, class: "btn btn-xs btn-danger" %>
          
        </div>
      </div>
    </div>
  </div>
<%= link_to 'Return to news listing', news_index_path, class: "btn btn-outline-success" %>

app/views/pages/about.html.erb
<h1>Acerca de mí</h1>

<%= link_to 'Listado de noticias', news_path %>
<%= link_to 'Home Page', root_path %>

app/views/pages/home.html.erb
<h1 class="text-center">Noticias Genosur</h1>

<div class="container py-4">
    <header class="pb-3 mb-4 border-bottom">
      <a href="https://www.genosur.com/es" class="d-flex align-items-center text-dark text-decoration-none">
        <span class="fs-4">Genosur</span>
      </a>
    </header>

    <div class="p-5 mb-4 bg-light rounded-3">
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Accede al Portal de Noticias de Genosur</h1>
        <p class="col-md-8 fs-4">Necesitarás crear una cuenta para visualizar las noticias.</p>
        <%= link_to "Sign In", login_path, class:"btn btn-primary btn-lg" %>
        <%= link_to "Sign Up", signup_path, class:"btn btn-primary btn-lg" %>
      </div>
    </div>
    </div>

app/views/users/_form.html.erb
<div class = "container">

  <% if @user.errors.any? %>
    <H2>Los siguientes errores previnieron la creación del usuario:</h2>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %> 
  <div class="row justify-content-center">
    <%= form_with data: { turbo: false}, class: "shadow p-3 mb-3 bg-white rounded", model: @user do |f| %>
      <div class="container shadow-lg p-3 mb-5 bg-white rounded">
        <div class="form-group row">
          <%= f.label :username, class: "col-2 col-form-label" %> <br/>
          <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Ingrese nombrede usuario" %> <br/><br/>
          <%= f.label :email, class: "col-2 col-form-label"  %><br/>
          <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Ingrese E-mail" %> <br/><br/>
        </div>
        <div class="form-group row">
          <%= f.label :password, class: "col-2 col-form-label" %> <br/>
          <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Ingresa tu nueva clave" %> <br/><br/>
        </div>
      </div>
      <div class="form-group row-text-center">
        <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-outline-dark btn-lg") %><br/>
      </div>
      <br/><br/>
      <% end %>
  </div>     
</div>

app/views/users/edit.html.erb
<div class="page-content">
  <h1 class="text-center mt-4 text-white">Edita tu Perfil</h1>
  <%= render 'form' %>
</div>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Bloggers</h1>

<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <%= link_to user.username, user %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to gravatar_for(user, size: 150), user %>
            </h5>
            <p class="card-text"><%= pluralize(user.news.count, "Noticias") %></p>
            <%= link_to "Ver Perfil", user, class: "btn btn-outline-success" %>
            <% if logged_in? and user == current_user %>
              <%= link_to "Editar Perfil", edit_user_path(user), class: "btn btn-outline-info" %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Registrado en: <%= time_ago_in_words(user.created_at) %></small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="page-content">
  <h1 class="text-center mt-4 text-white">Sign Up</h1>
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="page-content">
  <h1 class="text-center mt-4 text-white"><%= @user.username %> Perfil</h1>
  
  <div class="text-center mt-4">
    <% if logged_in? && @user == current_user %>
      <div class="text-center mt-4">
      <%= link_to "Edita tu perfil", edit_user_path(@user), class: "btn btn-outline-dark" %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <%= link_to @user.username, @user %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to gravatar_for(@user, size: 150), @user %>
            </h5>
            <p class="card-text"><%= pluralize(@user.news.count, "Noticias") %></p>
            <%= link_to "Ver Perfil", @user, class: "btn btn-outline-success" %>
            <% if logged_in? and @user == current_user %>
              <%= link_to "Editar Perfil", edit_user_path(@user), class: "btn btn-outline-info" %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Registrado hace: <%= time_ago_in_words(@user.created_at) %></small>
          </div>
        </div>
      </div>
    </div>
    </div>
  <% end %>
  
</div>